[theme]
primaryColor = "#27632C"         # Accent color (buttons, sliders, etc.)
backgroundColor = "#cbf1c7ff"      # App background
secondaryBackgroundColor = "#93bb96ff"  # Panels, cards background
textColor = "#0f3d13ff"        # Default text color
font = "sans serif"               # Options: "sans serif", "serif", "monospace"
